# Generated by Django 4.1.5 on 2023-01-27 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_char', models.CharField(max_length=500, verbose_name='Request to cnn')),
                ('answer_char', models.CharField(max_length=500, verbose_name='Answer rei')),
                ('request_date', models.DateTimeField(default=datetime.datetime(2023, 1, 27, 17, 23, 47, 693934, tzinfo=datetime.timezone.utc), verbose_name='Date created')),
            ],
        ),
    ]
