# Generated by Django 4.1.5 on 2023-01-27 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reiapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 27, 17, 28, 31, 702280, tzinfo=datetime.timezone.utc), verbose_name='Date created'),
        ),
    ]
